// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztdqjmmkbgwwbvbbjpsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0ZHFqbW1rYmd3d2J2YmJqcHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTIwNzYsImV4cCI6MjA2NTIyODA3Nn0.BC7Gj3bfZ9EQ-xB2meHZ7_f_nEc8l5jia-Z-kMtN5mU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);